### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by aitorjs** [p2pderivatives/cfd-dlc-js#38]
I get those errors when I run **npm run example** on the example:

```bash
 npm run example

> dlccli@0.0.1 example /home/ubuntu/cfd-dlc-js/examples/dlccli
> ts-node index.ts


/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
models/Oracle.ts:19:28 - error TS2339: Property 'GetSchnorrPublicNonce' does not exist on type 'typeof import("/home/ubuntu/cfd-dlc-js/index")'.

19     this.rValue = cfddlcjs.GetSchnorrPublicNonce({ kValue: this.kValue }).hex;
                              ~~~~~~~~~~~~~~~~~~~~~
models/Oracle.ts:29:33 - error TS2694: Namespace '"/home/ubuntu/cfd-dlc-js/index"' has no exported member 'SchnorrSignRequest'.

29     const signRequest: cfddlcjs.SchnorrSignRequest = {
                                   ~~~~~~~~~~~~~~~~~~
models/Oracle.ts:35:21 - error TS2339: Property 'SchnorrSign' does not exist on type 'typeof import("/home/ubuntu/cfd-dlc-js/index")'.

35     return cfddlcjs.SchnorrSign(signRequest).hex;
                       ~~~~~~~~~~~

    at createTSError (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntu/cfd-dlc-js/examples/dlccli/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlccli@0.0.1 example: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dlccli@0.0.1 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-10-28T17_28_36_156Z-debug.log

```

I taked a look to the last commit because I have the example running without this last commit. I see that at least there is a problem with those deleted lines https://github.com/p2pderivatives/cfd-dlc-js/commit/2acf68ff6e2cb83945f622b4f4f9f21a7f8b2c90#diff-e49e50514f78b3ffb47d032fa95ef504deb77512370ad37cbdbd05dd865cf0b9L197

I try without this last commit and the example runs. So, I guess that this last commit have some problems.

Thanks for the job and patient! :)

CHANGE1: **npm test** inside the root of the project, pass all the tests.

**Comment by Tibo-lg** [comment]
Thanks for reporting, I hadn't updated the example, should be fixed in #39
